"""
Generate interactive Plotly HTML dashboard from CSV benchmark results.

Reads:   results/*.csv  (generated by run_all_benchmarks.py)
Writes:  dashboard.html

Usage:   python generate_dashboard.py
"""

import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pandas as pd
import numpy as np
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
RESULTS_DIR = os.path.join(SCRIPT_DIR, "results")
OUTPUT_FILE = os.path.join(SCRIPT_DIR, "dashboard.html")

# Color scheme
COLORS = {
    "CUDA C FP32 (TF32=OFF)": "#2196F3",
    "CUDA C FP32 (TF32=ON)": "#1565C0",
    "CUDA C INT8 IGEMM": "#E91E63",
    "PyTorch FP32 GPU": "#4CAF50",
    "PyTorch INT8 torchao": "#FF9800",
    "ONNX FP32 GPU": "#00BCD4",
    "ONNX FP32 CPU": "#607D8B",
    "ONNX INT8 CPU": "#F44336",
}

CORE_COLORS = {
    "CUDA Core": "#2196F3",
    "Tensor Core": "#E91E63",
    "Memory/Elem": "#9E9E9E",
    "Other": "#BDBDBD",
}

RUNTIME_ORDER = [
    "CUDA C FP32 (TF32=OFF)", "CUDA C FP32 (TF32=ON)", "CUDA C INT8 IGEMM",
    "PyTorch FP32 GPU", "PyTorch INT8 torchao",
    "ONNX FP32 GPU", "ONNX FP32 CPU", "ONNX INT8 CPU",
]

COMMON_CONFIGS = ["4Kx4K (b=1)", "4Kx11K (b=1)", "8Kx8K (b=1)", "4Kx11K (b=32)"]

# Kernel name mapping for hover tooltips
KERNEL_MAP = {
    "CUDA C FP32 (TF32=OFF)": {"kernel": "ampere_sgemm / gemvx", "core": "CUDA Cores"},
    "CUDA C FP32 (TF32=ON)": {"kernel": "cutlass_tensorop / gemvx", "core": "Tensor Cores (GEMM) / CUDA Cores (GEMV)"},
    "CUDA C INT8 IGEMM": {"kernel": "cublasLt IMMA (s8_tensorop)", "core": "Tensor Cores"},
    "PyTorch FP32 GPU": {"kernel": "aten::mm → sgemm/tensorop", "core": "CUDA/Tensor (TF32 default)"},
    "PyTorch INT8 torchao": {"kernel": "dequant + sgemm", "core": "CUDA Cores (55% dequant overhead)"},
    "ONNX FP32 GPU": {"kernel": "cuBLAS via CUDAExecutionProvider", "core": "CUDA/Tensor Cores"},
    "ONNX FP32 CPU": {"kernel": "MLAS FP32 GEMM", "core": "CPU (AVX2/AVX-512)"},
    "ONNX INT8 CPU": {"kernel": "MLAS INT8 GEMM (VNNI)", "core": "CPU (VNNI INT8)"},
}


def load_csv(name):
    path = os.path.join(RESULTS_DIR, name)
    if not os.path.exists(path):
        print(f"  WARNING: {name} not found, skipping")
        return None
    return pd.read_csv(path)


def build_inference_chart(timing):
    """Chart 1: Inference Time Comparison (grouped bar chart)."""
    fig = go.Figure()
    runtimes = [r for r in RUNTIME_ORDER if r in timing["runtime"].unique()]

    for rt in runtimes:
        rt_data = timing[timing["runtime"] == rt]
        values, hovers = [], []
        for cfg in COMMON_CONFIGS:
            row = rt_data[rt_data["config"] == cfg]
            val = row["time_ms"].values[0] if len(row) > 0 else 0
            values.append(val)
            info = KERNEL_MAP.get(rt, {"kernel": "unknown", "core": "unknown"})
            std = row["std_ms"].values[0] if len(row) > 0 and "std_ms" in row.columns else 0
            hovers.append(
                f"<b>{rt}</b><br>"
                f"Config: {cfg}<br>"
                f"Time: {val:.3f} ms ± {std:.3f}<br>"
                f"Kernel: {info['kernel']}<br>"
                f"Core Type: {info['core']}"
            )

        fig.add_trace(go.Bar(
            name=rt, x=COMMON_CONFIGS, y=values,
            marker_color=COLORS.get(rt, "#999"),
            hovertext=hovers, hoverinfo="text",
        ))

    fig.update_layout(
        title="Inference Time: PyTorch vs CUDA C vs ONNX Runtime",
        xaxis_title="Matrix Configuration",
        yaxis_title="Inference Time (ms) — lower is better",
        barmode="group",
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        height=500,
    )
    return fig


def build_speedup_heatmap(timing):
    """Chart 2: Speedup Heatmap vs PyTorch FP32 GPU."""
    baseline = timing[timing["runtime"] == "PyTorch FP32 GPU"]
    runtimes = [r for r in RUNTIME_ORDER if r != "PyTorch FP32 GPU" and r in timing["runtime"].unique()]

    z, hover = [], []
    for rt in runtimes:
        row_vals, row_hover = [], []
        for cfg in COMMON_CONFIGS:
            base_row = baseline[baseline["config"] == cfg]
            rt_row = timing[(timing["runtime"] == rt) & (timing["config"] == cfg)]
            if len(base_row) > 0 and len(rt_row) > 0:
                speedup = base_row["time_ms"].values[0] / rt_row["time_ms"].values[0]
            else:
                speedup = 0
            row_vals.append(round(speedup, 2))
            marker = "FASTER" if speedup > 1.0 else "slower"
            row_hover.append(f"<b>{rt}</b><br>{cfg}<br>{speedup:.2f}x ({marker})")
        z.append(row_vals)
        hover.append(row_hover)

    short_names = [r.replace("CUDA C ", "CUDA ").replace("PyTorch ", "PT ").replace("ONNX ", "ONNX ") for r in runtimes]

    fig = go.Figure(data=go.Heatmap(
        z=z, x=COMMON_CONFIGS, y=short_names,
        colorscale=[[0, "#ef5350"], [0.22, "#FFEB3B"], [0.5, "#fff"], [1, "#4CAF50"]],
        zmin=0, zmax=4.5,
        text=[[f"{v:.2f}x" for v in row] for row in z],
        texttemplate="%{text}",
        hovertext=hover, hoverinfo="text",
        colorbar=dict(title="Speedup"),
    ))

    fig.update_layout(
        title="Speedup vs PyTorch FP32 GPU (>1x = faster)",
        height=400,
    )
    return fig


def build_core_breakdown(profiling):
    """Chart 3: Core Type Breakdown (stacked bar, split by batch)."""
    if profiling is None:
        return None

    core_types = ["CUDA Core", "Tensor Core", "Memory/Elem", "Other"]
    fig = make_subplots(rows=1, cols=2, subplot_titles=["batch=1 (GEMV)", "batch=32 (GEMM)"])

    for col, batch in enumerate([1, 32], 1):
        df = profiling[profiling["batch"] == batch]
        sessions = [s.split(" (")[0] for s in df["session"].tolist()]

        for ct in core_types:
            if ct in df.columns:
                values = df[ct].fillna(0).values.astype(float)
                if values.max() > 0:
                    hovers = [
                        f"<b>{sess}</b><br>{ct}: {v:.1f}%"
                        for sess, v in zip(sessions, values)
                    ]
                    fig.add_trace(go.Bar(
                        name=ct, x=sessions, y=values,
                        marker_color=CORE_COLORS.get(ct, "#999"),
                        hovertext=hovers, hoverinfo="text",
                        showlegend=(col == 1),
                    ), row=1, col=col)

    fig.update_layout(
        barmode="stack",
        title="GPU Core Type Breakdown — Which Cores Does Each Method Use?",
        yaxis_title="% of GPU Time",
        height=450,
    )
    return fig


def build_error_chart(pt_error, onnx_error, cuda_error):
    """Chart 4: Quantization Error."""
    fig = make_subplots(rows=1, cols=2,
                        subplot_titles=["Small Demo Error", "LLM-Scale ONNX INT8 Error"])

    # Left: small demo
    methods, errors, colors = [], [], []
    if pt_error is not None:
        for _, row in pt_error.iterrows():
            methods.append(row["method"])
            errors.append(row["mean_abs_error"])
            colors.append("#FF9800" if "torchao" in str(row["method"]) else "#4CAF50")
    if cuda_error is not None:
        for _, row in cuda_error.iterrows():
            methods.append(row["method"])
            errors.append(row["mean_abs_error"])
            colors.append("#E91E63")

    if methods:
        hovers = [f"<b>{m}</b><br>Error: {e:.6f}" for m, e in zip(methods, errors)]
        fig.add_trace(go.Bar(
            x=methods, y=errors, marker_color=colors,
            hovertext=hovers, hoverinfo="text", showlegend=False,
        ), row=1, col=1)

    # Right: LLM-scale ONNX INT8
    if onnx_error is not None:
        int8_err = onnx_error[onnx_error["runtime"] == "ONNX INT8 CPU"]
        if len(int8_err) > 0:
            configs_e = int8_err["config"].tolist()
            vals = int8_err["mean_abs_error"].astype(float).values
            hovers = [f"<b>{c}</b><br>Error: {v:.6f}" for c, v in zip(configs_e, vals)]
            fig.add_trace(go.Bar(
                x=configs_e, y=vals, marker_color="#F44336",
                hovertext=hovers, hoverinfo="text", showlegend=False,
            ), row=1, col=2)

    fig.update_layout(
        title="Quantization Error: How Much Accuracy Do We Lose?",
        height=400,
    )
    fig.update_yaxes(title_text="Mean Absolute Error", row=1, col=1)
    fig.update_yaxes(title_text="Mean Absolute Error vs FP32", row=1, col=2)
    return fig


def build_model_size(onnx_error):
    """Chart 5: Model Size Comparison."""
    if onnx_error is None:
        return None

    int8_rows = onnx_error[(onnx_error["runtime"] == "ONNX INT8 CPU") &
                            (onnx_error["fp32_size_kb"].notna())]
    if len(int8_rows) == 0:
        return None

    configs_s = int8_rows["config"].tolist()
    fp32_mb = int8_rows["fp32_size_kb"].astype(float).values / 1024
    int8_mb = int8_rows["int8_size_kb"].astype(float).values / 1024

    fig = go.Figure()
    fig.add_trace(go.Bar(
        name="FP32 (4 bytes/weight)", x=configs_s, y=fp32_mb,
        marker_color="#4CAF50",
        hovertemplate="<b>%{x}</b><br>FP32: %{y:.1f} MB<extra></extra>",
    ))
    fig.add_trace(go.Bar(
        name="INT8 (1 byte/weight)", x=configs_s, y=int8_mb,
        marker_color="#E91E63",
        hovertemplate="<b>%{x}</b><br>INT8: %{y:.1f} MB<extra></extra>",
    ))

    # Add compression ratio annotations
    for i, cfg in enumerate(configs_s):
        ratio = fp32_mb[i] / int8_mb[i]
        fig.add_annotation(
            x=cfg, y=fp32_mb[i] * 0.7,
            text=f"{ratio:.1f}x smaller", showarrow=False,
            font=dict(size=12, color="#E91E63", family="Arial Black"),
        )

    fig.update_layout(
        title="ONNX Model Size: FP32 vs INT8 (4x Compression)",
        yaxis_title="Model Size (MB)",
        barmode="group",
        height=400,
    )
    return fig


def build_ollama_section(ollama_timing):
    """Dedicated Ollama section: real model inference comparison."""
    if ollama_timing is None:
        return None, None

    # Chart A: Inference time + model metadata
    models = ollama_timing["model"].tolist()
    short_names = [m.split("/")[-1].split(":")[0] for m in models]
    times = ollama_timing["inference_ms"].astype(float).values
    stds = ollama_timing["std_ms"].astype(float).values

    hovers = []
    for _, row in ollama_timing.iterrows():
        hovers.append(
            f"<b>{row['model']}</b><br>"
            f"Family: {row['family']}<br>"
            f"Parameters: {row['parameters']}<br>"
            f"Quantization: {row['quantization']}<br>"
            f"Model Size: {row['model_size_mb']} MB<br>"
            f"Inference: {row['inference_ms']} ms ± {row['std_ms']} ms<br>"
            f"Tokens/call: {row['avg_tokens']}<br>"
            f"GPU: {row['gpu_percent']}<br>"
            f"VRAM: {row['vram_mb']} MB"
        )

    quant_types = ollama_timing["quantization"].tolist()
    bar_colors = ["#E91E63" if "Q4" in q or "Q8" in q or "INT" in q.upper()
                  else "#4CAF50" for q in quant_types]

    labels = [f"{n}\n({q})" for n, q in zip(short_names, quant_types)]

    fig_time = go.Figure()
    fig_time.add_trace(go.Bar(
        x=labels, y=times,
        error_y=dict(type="data", array=stds, visible=True),
        marker_color=bar_colors,
        hovertext=hovers, hoverinfo="text",
    ))
    fig_time.update_layout(
        title="Ollama Inference Time: Quantized vs Full Precision",
        yaxis_title="Inference Time (ms) — lower is better",
        height=400,
    )

    # Chart B: VRAM usage + GPU allocation
    vram_vals = ollama_timing["vram_mb"].astype(float).values
    model_sizes = ollama_timing["model_size_mb"].astype(float).values
    gpu_pcts = []
    for gp in ollama_timing["gpu_percent"]:
        try:
            gpu_pcts.append(float(str(gp).replace("%", "")))
        except (ValueError, TypeError):
            gpu_pcts.append(0)

    fig_vram = make_subplots(rows=1, cols=2,
                              subplot_titles=["VRAM Usage", "GPU Offload %"])

    hovers_vram = [
        f"<b>{m}</b><br>VRAM: {v:.0f} MB<br>Model: {s:.0f} MB on disk"
        for m, v, s in zip(models, vram_vals, model_sizes)
    ]
    fig_vram.add_trace(go.Bar(
        x=labels, y=vram_vals, marker_color=bar_colors,
        hovertext=hovers_vram, hoverinfo="text", showlegend=False,
    ), row=1, col=1)

    # Add 6GB VRAM limit line
    fig_vram.add_hline(y=6144, line_dash="dash", line_color="red",
                        annotation_text="6 GB VRAM limit", row=1, col=1)

    hovers_gpu = [f"<b>{m}</b><br>GPU: {g:.0f}%" for m, g in zip(models, gpu_pcts)]
    fig_vram.add_trace(go.Bar(
        x=labels, y=gpu_pcts,
        marker_color=["#4CAF50" if g >= 90 else "#FF9800" if g >= 50 else "#F44336"
                       for g in gpu_pcts],
        hovertext=hovers_gpu, hoverinfo="text", showlegend=False,
    ), row=1, col=2)

    fig_vram.update_yaxes(title_text="VRAM (MB)", row=1, col=1)
    fig_vram.update_yaxes(title_text="GPU Offload %", range=[0, 110], row=1, col=2)
    fig_vram.update_layout(
        title="VRAM Usage & GPU Offload",
        height=400,
    )

    return fig_time, fig_vram


def build_html(figures, ollama_figs):
    """Assemble all charts into a single HTML file."""
    html_parts = ["""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>FP32→INT8 Quantization Benchmark Dashboard</title>
<style>
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    max-width: 1200px; margin: 0 auto; padding: 20px;
    background: #f5f5f5; color: #333;
  }
  h1 { color: #1a1a1a; border-bottom: 3px solid #E91E63; padding-bottom: 10px; }
  h2 { color: #1565C0; margin-top: 40px; }
  .section { background: white; border-radius: 8px; padding: 20px; margin: 20px 0;
             box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
  .intro { font-size: 1.1em; line-height: 1.6; }
  .key-finding { background: #FFF3E0; border-left: 4px solid #FF9800;
                 padding: 12px 16px; margin: 10px 0; border-radius: 0 4px 4px 0; }
  .ollama-note { background: #E3F2FD; border-left: 4px solid #2196F3;
                 padding: 12px 16px; margin: 10px 0; border-radius: 0 4px 4px 0; }
  .chart { margin: 20px 0; }
  footer { text-align: center; color: #999; margin-top: 40px; font-size: 0.9em; }
</style>
</head>
<body>

<h1>FP32→INT8 Quantization Benchmark Dashboard</h1>

<div class="section intro">
<p>Interactive benchmark comparing <b>FP32 vs INT8 quantization</b> across
<b>PyTorch</b>, <b>CUDA C (cuBLAS)</b>, and <b>ONNX Runtime</b>.
Hover over any bar to see kernel names, core types, and exact timings.</p>

<div class="key-finding">
<b>Key Finding:</b> CUDA C INT8 is 3-4x faster than FP32 (true INT8×INT8 on Tensor Cores),
while PyTorch torchao INT8 is 2x <i>slower</i> (dequantization overhead dominates).
</div>
</div>

<h2>1. Inference Time Comparison</h2>
<div class="section chart" id="chart-inference"></div>

<h2>2. Speedup Heatmap</h2>
<div class="section chart" id="chart-speedup"></div>

<h2>3. GPU Core Type Breakdown</h2>
<div class="section chart" id="chart-cores"></div>

<h2>4. Quantization Error</h2>
<div class="section chart" id="chart-error"></div>

<h2>5. Model Size Compression</h2>
<div class="section chart" id="chart-size"></div>
"""]

    # Ollama section
    if ollama_figs[0] is not None:
        html_parts.append("""
<h2>6. Real-World Context: Running Quantized Models via Ollama</h2>
<div class="section">
<div class="ollama-note">
<b>Note:</b> This section shows real LLM inference via <b>Ollama</b>, not synthetic
matrix multiplications. Ollama uses <b>GGUF Q4_K_M</b> (4-bit) quantization — a different
scheme than the INT8 (8-bit) benchmarks above. The comparison shows how quantization
works in practice: smaller models fit in GPU VRAM, run faster, and use less memory.
</div>
</div>
<div class="section chart" id="chart-ollama-time"></div>
<div class="section chart" id="chart-ollama-vram"></div>
""")

    html_parts.append("""
<footer>
<p>Generated by generate_dashboard.py | Hardware: NVIDIA RTX A3000 Laptop GPU (6 GB)</p>
<p>Source: <a href="https://github.com/sumit-ai-ml/fp32-to-int8-quantization">github.com/sumit-ai-ml/fp32-to-int8-quantization</a></p>
</footer>

</body>
</html>""")

    html = "\n".join(html_parts)

    # Embed Plotly charts as divs
    chart_ids = ["chart-inference", "chart-speedup", "chart-cores", "chart-error", "chart-size"]
    for fig, div_id in zip(figures, chart_ids):
        if fig is not None:
            chart_html = fig.to_html(full_html=False, include_plotlyjs=False, div_id=div_id)
            html = html.replace(f'<div class="section chart" id="{div_id}"></div>',
                                f'<div class="section chart">{chart_html}</div>')

    # Embed Ollama charts
    if ollama_figs[0] is not None:
        for fig, div_id in zip(ollama_figs, ["chart-ollama-time", "chart-ollama-vram"]):
            if fig is not None:
                chart_html = fig.to_html(full_html=False, include_plotlyjs=False, div_id=div_id)
                html = html.replace(f'<div class="section chart" id="{div_id}"></div>',
                                    f'<div class="section chart">{chart_html}</div>')

    # Add Plotly.js (bundled inline for offline use)
    import plotly
    plotly_js = f'<script src="https://cdn.plot.ly/plotly-{plotly.__version__}.min.js"></script>'
    # Use bundled version for offline support
    plotly_js_inline = f'<script>{plotly.offline.get_plotlyjs()}</script>'
    html = html.replace("</head>", f"{plotly_js_inline}\n</head>")

    return html


def main():
    print("Loading CSVs from results/ ...")
    pt_timing = load_csv("pytorch_timing.csv")
    cuda_timing = load_csv("cuda_timing.csv")
    onnx_timing = load_csv("onnx_timing.csv")
    profiling = load_csv("profiling.csv")
    pt_error = load_csv("pytorch_error.csv")
    onnx_error = load_csv("onnx_error.csv")
    cuda_error = load_csv("cuda_error.csv")
    ollama_timing = load_csv("ollama_timing.csv")

    # Merge timing data
    all_timing = pd.concat([
        df for df in [pt_timing, cuda_timing, onnx_timing] if df is not None
    ], ignore_index=True)
    all_timing["time_ms"] = pd.to_numeric(all_timing["time_ms"], errors="coerce")
    if "std_ms" in all_timing.columns:
        all_timing["std_ms"] = pd.to_numeric(all_timing["std_ms"], errors="coerce").fillna(0)
    timing = all_timing[all_timing["config"].isin(COMMON_CONFIGS)].copy()

    print("Building charts...")
    fig1 = build_inference_chart(timing)
    print("  [1/5] Inference time")

    fig2 = build_speedup_heatmap(timing)
    print("  [2/5] Speedup heatmap")

    fig3 = build_core_breakdown(profiling)
    print("  [3/5] Core breakdown")

    fig4 = build_error_chart(pt_error, onnx_error, cuda_error)
    print("  [4/5] Quantization error")

    fig5 = build_model_size(onnx_error)
    print("  [5/5] Model size")

    ollama_figs = build_ollama_section(ollama_timing)
    if ollama_figs[0] is not None:
        print("  [+] Ollama section")

    print("Assembling HTML...")
    html = build_html([fig1, fig2, fig3, fig4, fig5], ollama_figs)

    with open(OUTPUT_FILE, "w") as f:
        f.write(html)

    size_mb = os.path.getsize(OUTPUT_FILE) / (1024 * 1024)
    print(f"\nDashboard written to: {OUTPUT_FILE} ({size_mb:.1f} MB)")


if __name__ == "__main__":
    main()
