"""
Generate all plots from CSV benchmark results.

Reads:   results/*.csv  (generated by run_all_benchmarks.py)
Writes:  plots/*.png

Usage:   python generate_plots.py
"""

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
import pandas as pd
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
RESULTS_DIR = os.path.join(SCRIPT_DIR, "results")
PLOT_DIR = os.path.join(SCRIPT_DIR, "plots")
os.makedirs(PLOT_DIR, exist_ok=True)

# ── Style ──
plt.rcParams.update({
    "figure.facecolor": "white", "axes.facecolor": "#f8f9fa",
    "axes.grid": True, "grid.alpha": 0.3, "font.size": 11,
    "axes.titlesize": 14, "axes.titleweight": "bold", "figure.dpi": 150,
})

COLORS = {
    "CUDA C FP32 (TF32=OFF)": "#2196F3",
    "CUDA C FP32 (TF32=ON)": "#1565C0",
    "CUDA C INT8 IGEMM": "#E91E63",
    "PyTorch FP32 GPU": "#4CAF50",
    "PyTorch INT8 torchao": "#FF9800",
    "ONNX FP32 GPU": "#00BCD4",
    "ONNX FP32 CPU": "#607D8B",
    "ONNX INT8 CPU": "#F44336",
}

# ── Load CSVs ──
def load_csv(name):
    path = os.path.join(RESULTS_DIR, name)
    if not os.path.exists(path):
        print(f"  WARNING: {name} not found, skipping")
        return None
    return pd.read_csv(path)

print("Loading CSVs from results/ ...")
pt_timing = load_csv("pytorch_timing.csv")
cuda_timing = load_csv("cuda_timing.csv")
onnx_timing = load_csv("onnx_timing.csv")
profiling = load_csv("profiling.csv")
pt_error = load_csv("pytorch_error.csv")
onnx_error = load_csv("onnx_error.csv")
cuda_error = load_csv("cuda_error.csv")

# ── Merge all timing into one DataFrame ──
all_timing = pd.concat([
    df for df in [pt_timing, cuda_timing, onnx_timing] if df is not None
], ignore_index=True)
all_timing["time_ms"] = pd.to_numeric(all_timing["time_ms"], errors="coerce")

# Normalize config names (CUDA C may have slightly different names)
all_timing["config"] = all_timing["config"].str.replace("11264", "11K", regex=False)
# Already has 11K in most cases, just ensure consistency

# Common configs (only those present in all 3 runtimes)
common_configs = ["4Kx4K (b=1)", "4Kx11K (b=1)", "8Kx8K (b=1)", "4Kx11K (b=32)"]

# Filter to common configs
timing = all_timing[all_timing["config"].isin(common_configs)].copy()

# Order for runtimes
RUNTIME_ORDER = [
    "CUDA C FP32 (TF32=OFF)", "CUDA C FP32 (TF32=ON)", "CUDA C INT8 IGEMM",
    "PyTorch FP32 GPU", "PyTorch INT8 torchao",
    "ONNX FP32 GPU", "ONNX FP32 CPU", "ONNX INT8 CPU",
]


# ══════════════════════════════════════════════
# PLOT 1: Inference Time Comparison
# ══════════════════════════════════════════════
def plot_inference_time():
    fig, ax = plt.subplots(figsize=(16, 8))

    runtimes = [r for r in RUNTIME_ORDER if r in timing["runtime"].unique()]
    x = np.arange(len(common_configs))
    n = len(runtimes)
    width = 0.8 / n

    for i, rt in enumerate(runtimes):
        rt_data = timing[timing["runtime"] == rt]
        values = []
        for cfg in common_configs:
            row = rt_data[rt_data["config"] == cfg]
            values.append(row["time_ms"].values[0] if len(row) > 0 else 0)
        offset = (i - n / 2 + 0.5) * width
        color = COLORS.get(rt, "#999")
        bars = ax.bar(x + offset, values, width * 0.9, label=rt, color=color,
                      edgecolor="white", linewidth=0.5)
        # Label the winner (CUDA C INT8)
        if "INT8 IGEMM" in rt:
            for bar, val in zip(bars, values):
                ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.03,
                        f'{val:.3f}', ha='center', va='bottom', fontsize=7,
                        fontweight='bold', color=COLORS.get(rt, "red"))

    ax.set_xlabel("Matrix Configuration")
    ax.set_ylabel("Inference Time (ms) — lower is better")
    ax.set_title("Inference Time: PyTorch vs CUDA C vs ONNX Runtime\n(from results/pytorch_timing.csv, cuda_timing.csv, onnx_timing.csv)")
    ax.set_xticks(x)
    ax.set_xticklabels(common_configs)
    ax.legend(loc="upper left", ncol=4, fontsize=8)

    plt.tight_layout()
    plt.savefig(os.path.join(PLOT_DIR, "01_inference_time.png"), bbox_inches="tight")
    plt.close()
    print("  [1/6] Inference time comparison")


# ══════════════════════════════════════════════
# PLOT 2: Speedup Heatmap
# ══════════════════════════════════════════════
def plot_speedup_heatmap():
    # Baseline = PyTorch FP32 GPU
    baseline = timing[timing["runtime"] == "PyTorch FP32 GPU"]

    runtimes = [r for r in RUNTIME_ORDER if r != "PyTorch FP32 GPU" and r in timing["runtime"].unique()]
    data = np.zeros((len(runtimes), len(common_configs)))

    for i, rt in enumerate(runtimes):
        for j, cfg in enumerate(common_configs):
            base_row = baseline[baseline["config"] == cfg]
            rt_row = timing[(timing["runtime"] == rt) & (timing["config"] == cfg)]
            if len(base_row) > 0 and len(rt_row) > 0:
                data[i, j] = base_row["time_ms"].values[0] / rt_row["time_ms"].values[0]

    fig, ax = plt.subplots(figsize=(12, 6))
    im = ax.imshow(data, cmap="RdYlGn", aspect="auto", vmin=0, vmax=4.5)

    ax.set_xticks(range(len(common_configs)))
    ax.set_xticklabels(common_configs)
    ax.set_yticks(range(len(runtimes)))
    ax.set_yticklabels([r.replace("CUDA C ", "CUDA\n").replace("ONNX ", "ONNX\n").replace("PyTorch ", "PT\n") for r in runtimes], fontsize=9)

    for i in range(len(runtimes)):
        for j in range(len(common_configs)):
            val = data[i, j]
            color = "white" if val > 3.0 or val < 0.3 else "black"
            marker = "FASTER" if val > 1.0 else "slower"
            ax.text(j, i, f"{val:.2f}x\n{marker}", ha="center", va="center",
                    fontsize=9, fontweight="bold", color=color)

    ax.set_title("Speedup vs PyTorch FP32 GPU (>1x = faster)\n(computed from CSV data)")
    plt.colorbar(im, ax=ax, label="Speedup", shrink=0.8)
    plt.tight_layout()
    plt.savefig(os.path.join(PLOT_DIR, "02_speedup_heatmap.png"), bbox_inches="tight")
    plt.close()
    print("  [2/6] Speedup heatmap")


# ══════════════════════════════════════════════
# PLOT 3: Core Type Breakdown (from profiling.csv)
# ══════════════════════════════════════════════
def plot_core_breakdown():
    if profiling is None:
        print("  [3/6] SKIPPED (no profiling.csv)")
        return

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    core_colors = {"CUDA Core": "#2196F3", "Tensor Core": "#E91E63", "Memory/Elem": "#9E9E9E", "Other": "#BDBDBD"}
    core_types = ["CUDA Core", "Tensor Core", "Memory/Elem", "Other"]

    for ax_idx, batch in enumerate([1, 32]):
        ax = axes[ax_idx]
        df = profiling[profiling["batch"] == batch]
        sessions = df["session"].tolist()
        x = np.arange(len(sessions))
        bottoms = np.zeros(len(sessions))

        for ct in core_types:
            if ct in df.columns:
                values = df[ct].fillna(0).values.astype(float)
                if values.max() > 0:
                    ax.bar(x, values, 0.5, bottom=bottoms, label=ct,
                           color=core_colors[ct], edgecolor="white")
                    for i, v in enumerate(values):
                        if v > 5:
                            ax.text(x[i], bottoms[i] + v / 2, f"{v:.1f}%",
                                    ha="center", va="center", fontsize=10,
                                    fontweight="bold", color="white" if v > 20 else "black")
                    bottoms += values

        op = "GEMV" if batch == 1 else "GEMM"
        ax.set_title(f"batch={batch} ({op}) — Which GPU Cores?\n(from results/profiling.csv)")
        ax.set_ylabel("% of GPU Time")
        ax.set_xticks(x)
        ax.set_xticklabels([s.split(" (")[0] for s in sessions], fontsize=9)
        ax.set_ylim(0, 105)
        ax.legend(fontsize=8)

    plt.tight_layout()
    plt.savefig(os.path.join(PLOT_DIR, "03_core_breakdown.png"), bbox_inches="tight")
    plt.close()
    print("  [3/6] Core type breakdown")


# ══════════════════════════════════════════════
# PLOT 4: Quantization Error
# ══════════════════════════════════════════════
def plot_error():
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

    # Left: small demo error (from pytorch_error.csv + cuda_error.csv)
    methods, errors, colors = [], [], []
    if pt_error is not None:
        for _, row in pt_error.iterrows():
            methods.append(row["method"])
            errors.append(row["mean_abs_error"])
            colors.append("#FF9800" if "torchao" in row["method"] else "#4CAF50")
    if cuda_error is not None:
        for _, row in cuda_error.iterrows():
            methods.append(row["method"])
            errors.append(row["mean_abs_error"])
            colors.append("#E91E63")

    ax1.bar(range(len(methods)), errors, color=colors, edgecolor="white")
    for i, (m, e) in enumerate(zip(methods, errors)):
        label = f"{e:.6f}" if e > 0 else "0 (exact)"
        ax1.text(i, e + max(errors) * 0.02, label, ha="center", fontsize=8, fontweight="bold")
    ax1.set_title("Quantization Error (Small Demo)\n(from results/pytorch_error.csv, cuda_error.csv)")
    ax1.set_ylabel("Mean Absolute Error")
    ax1.set_xticks(range(len(methods)))
    ax1.set_xticklabels(methods, fontsize=9, rotation=15)

    # Right: LLM-scale error (from onnx_error.csv)
    if onnx_error is not None:
        int8_err = onnx_error[onnx_error["runtime"] == "ONNX INT8 CPU"]
        configs_e = int8_err["config"].tolist()
        x = np.arange(len(configs_e))
        ax2.bar(x, int8_err["mean_abs_error"].astype(float).values, color="#F44336", edgecolor="white")
        for i, v in enumerate(int8_err["mean_abs_error"].astype(float).values):
            ax2.text(i, v + 0.03, f"{v:.3f}", ha="center", fontsize=9, fontweight="bold")
        ax2.set_title("ONNX INT8 Error at LLM Scale\n(from results/onnx_error.csv)")
        ax2.set_ylabel("Mean Absolute Error vs FP32")
        ax2.set_xticks(x)
        ax2.set_xticklabels(configs_e, fontsize=9)

    plt.tight_layout()
    plt.savefig(os.path.join(PLOT_DIR, "04_quantization_error.png"), bbox_inches="tight")
    plt.close()
    print("  [4/6] Quantization error")


# ══════════════════════════════════════════════
# PLOT 5: Model Size Compression
# ══════════════════════════════════════════════
def plot_model_size():
    if onnx_error is None:
        print("  [5/6] SKIPPED (no onnx_error.csv)")
        return

    int8_rows = onnx_error[(onnx_error["runtime"] == "ONNX INT8 CPU") &
                            (onnx_error["fp32_size_kb"].notna())]

    if len(int8_rows) == 0:
        print("  [5/6] SKIPPED (no size data)")
        return

    fig, ax = plt.subplots(figsize=(10, 6))
    configs_s = int8_rows["config"].tolist()
    fp32_mb = int8_rows["fp32_size_kb"].astype(float).values / 1024
    int8_mb = int8_rows["int8_size_kb"].astype(float).values / 1024

    x = np.arange(len(configs_s))
    width = 0.3
    ax.bar(x - width / 2, fp32_mb, width, label="FP32 (4 bytes/weight)", color="#4CAF50")
    ax.bar(x + width / 2, int8_mb, width, label="INT8 (1 byte/weight)", color="#E91E63")

    for i in range(len(configs_s)):
        ratio = fp32_mb[i] / int8_mb[i]
        ax.text(x[i], fp32_mb[i] * 0.6, f"{ratio:.2f}x\nsmaller",
                ha="center", fontsize=9, fontweight="bold", color="red")

    ax.set_title("ONNX Model Size: FP32 vs INT8\n(from results/onnx_error.csv)")
    ax.set_ylabel("Model Size (MB)")
    ax.set_xticks(x)
    ax.set_xticklabels(configs_s)
    ax.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(PLOT_DIR, "05_model_size.png"), bbox_inches="tight")
    plt.close()
    print("  [5/6] Model size")


# ══════════════════════════════════════════════
# PLOT 6: Data Path Diagram (static, explanatory)
# ══════════════════════════════════════════════
def plot_data_paths():
    fig, axes = plt.subplots(3, 1, figsize=(14, 10))
    for ax in axes:
        ax.set_xlim(0, 10); ax.set_ylim(0, 2); ax.axis("off")

    def box(ax, x, y, text, color):
        rect = mpatches.FancyBboxPatch((x, y - 0.35), 1.3, 0.7, boxstyle="round,pad=0.1",
                                         facecolor=color, alpha=0.15, edgecolor=color, linewidth=2)
        ax.add_patch(rect)
        ax.text(x + 0.65, y, text, ha="center", va="center", fontsize=9, fontweight="bold", color=color)

    def arrow(ax, x1, y1, x2, y2):
        ax.annotate("", xy=(x2, y2), xytext=(x1, y1), arrowprops=dict(arrowstyle="->", color="#333", lw=2))

    # Path A: CUDA C INT8
    ax = axes[0]
    ax.set_title("CUDA C INT8: True INT8 x INT8 on Tensor Cores (FASTEST)", fontsize=12,
                 color="#E91E63", fontweight="bold", loc="left")
    box(ax, 0.5, 1.0, "INT8\nWeights", "#E91E63")
    arrow(ax, 2.0, 1.0, 2.8, 1.0)
    box(ax, 3.0, 1.0, "Tensor Core\nIMMA\nINT8xINT8", "#E91E63")
    arrow(ax, 4.5, 1.0, 5.3, 1.0)
    box(ax, 5.5, 1.0, "INT32\nAccum", "#9C27B0")
    arrow(ax, 7.0, 1.0, 7.8, 1.0)
    box(ax, 8.0, 1.0, "FP32\nOutput", "#4CAF50")
    ax.text(5, 0.2, "No dequant before matmul -- 4x less data + native INT8 compute",
            ha="center", fontsize=10, style="italic", color="#E91E63")

    # Path B: PyTorch torchao
    ax = axes[1]
    ax.set_title("PyTorch torchao INT8: Dequant to FP32 first, then FP32 GEMM (SLOWEST)", fontsize=12,
                 color="#FF9800", fontweight="bold", loc="left")
    box(ax, 0.5, 1.0, "INT8\nWeights", "#FF9800")
    arrow(ax, 2.0, 1.0, 2.8, 1.0)
    box(ax, 3.0, 1.0, "DEQUANT\nINT8->FP32\n55% time!", "#F44336")
    arrow(ax, 4.5, 1.0, 5.3, 1.0)
    box(ax, 5.5, 1.0, "FP32\nGEMM", "#2196F3")
    arrow(ax, 7.0, 1.0, 7.8, 1.0)
    box(ax, 8.0, 1.0, "FP32\nOutput", "#4CAF50")
    ax.text(5, 0.2, "Dequant overhead (55% of GPU time) makes it SLOWER than plain FP32",
            ha="center", fontsize=10, style="italic", color="#F44336")

    # Path C: ONNX INT8 CPU
    ax = axes[2]
    ax.set_title("ONNX INT8 CPU: Native INT8 GEMM via MLAS (fast for small matrices)", fontsize=12,
                 color="#F44336", fontweight="bold", loc="left")
    box(ax, 0.5, 1.0, "INT8\nWeights", "#F44336")
    arrow(ax, 2.0, 1.0, 2.8, 1.0)
    box(ax, 3.0, 1.0, "Quantize\nActivations\n(runtime)", "#FF5722")
    arrow(ax, 4.5, 1.0, 5.3, 1.0)
    box(ax, 5.5, 1.0, "MLAS\nINT8xINT8\n(VNNI)", "#F44336")
    arrow(ax, 7.0, 1.0, 7.8, 1.0)
    box(ax, 8.0, 1.0, "FP32\nOutput", "#4CAF50")
    ax.text(5, 0.2, "No GPU launch overhead -- small weights fit in CPU L3 cache",
            ha="center", fontsize=10, style="italic", color="#F44336")

    plt.tight_layout()
    plt.savefig(os.path.join(PLOT_DIR, "06_data_paths.png"), bbox_inches="tight")
    plt.close()
    print("  [6/6] Data path diagrams")


# ══════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════
if __name__ == "__main__":
    print("Generating plots from CSV data...\n")
    plot_inference_time()
    plot_speedup_heatmap()
    plot_core_breakdown()
    plot_error()
    plot_model_size()
    plot_data_paths()
    print(f"\nAll plots saved to: {PLOT_DIR}/")
